//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspnet_mvc.Models.veritabanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class arac_bilgileri
    {
        public int arac_id { get; set; }
        public string arac_plaka { get; set; }
        public string arac_marka { get; set; }
        public string arac_renk { get; set; }
        public int kisi_id { get; set; }
    }
}
