//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspnet_mvc.Models.veritabanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class kisi_bilgileri
    {
        public int kisi_id { get; set; }
        public string tc_kimlik { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string cep_telefonu { get; set; }
        public string Adres { get; set; }
    }
}
